print(" PATTERN A     PATTERN B    PATTERN C     PATTERN D")
print(" *             * * * * * *            *   * * * * * *")
print(" * *           * * * * *            * *     * * * * *")
print(" * * *         * * * *            * * *       * * * *")
print(" * * * *       * * *            * * * *         * * *")
print(" * * * * *     * *            * * * * *           * *")
print(" * * * * * *   *            * * * * * *             *")